(require 'find-file-in-project)
(require 'dash)

;; gets a listing of all files in a directory filtering out ones that are uninteresting
(defun get-clean-file-listing (directory)
  (remove-if #'file-symlink-p
             (mapcar (lambda (file)
                     ;; add full path
                     (concat (file-name-as-directory directory) file))
                     (remove-if (lambda (file)
                                  (or
                                   ;; remove hidden directories
                                   (string= (subseq file 0 1) ".")
                                   ;; don't search the target directory at project root
                                   ;; (files generated by build)
                                   (and
                                    (equal directory (ffip-project-root))
                                    (equal file "target"))))
                                (directory-files directory)))))

;; alternate implentation of file-file-in-project
(defun directory-files-recursive (directory)
  (-flatten
   (mapcar (lambda (file)
           (if (file-directory-p file)
               (directory-files-recursive file)
             file))
         (get-clean-file-listing directory))))

(defun find-file-in-project-wrapper ()
  "Wrapper around find-file-in-project to speed it up when there is no filter on file types to be searched"
  (interactive)
  (let ((file (ido-completing-read "Choose file: " (directory-files-recursive (ffip-project-root)) nil t)))
    (when file
      (find-file file))))

(provide 'find-file-in-project-extension)
